from . import product
from . import project_project
from . import res_kantor
from . import kelompok_proyek
from . import res_bidang
from . import res_sub_bidang
from . import status_proyek
from . import supplier_category
from . import supplier_service
from . import res_partner